name: Update OTEL Builder Dependencies
on:
  push:
    branches:
      - dependabot/go_modules/src/otel-collector-builder/**
  pull_request:
    branches:
      - dependabot/go_modules/src/otel-collector-builder/**

jobs:
  run:
    name: Update the
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: src/otel-collector/go.mod

      - run: go version

      - name: Update the OTEL builder version inside the configuration
        run: |
          extract_version() {
            local s="$1"
            [[ $s =~ ([0-9]+(\.[0-9]+){2})$ ]] && printf '%s\n' "${BASH_REMATCH[1]}"
          }
          otel_builder_version=$(extract_version "${{ github.ref_name }}")
          sed -E -i '' "s#^(\\s*require\\s+go\\.opentelemetry\\.io/collector/cmd/builder\\s+)v?[0-9]+(\\.[0-9]+){2}#\\1v${otel_builder_version}#" src/otel-collector-builder/go.mod

      - name: Build the new OTEL collector version
        shell: bash
        run: scripts/regenerate-otel-collector-distribution

      - name: Run the Integrationtest
        shell: bash
        run: scripts/subtests/integration-test

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Adjust the OTEL builder version
          branch: ${{ github.head_ref }}
